name: Run Unit Tests On Jest
on:
  pull_request:
    branches: [ main, dev ]
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x]
    
    steps:
      - uses: actions/checkout@v2
      - name: Using node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - run: npm test
        




